apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: sameersbn/redis
          ports:
            - containerPort: 6379
              protocol: TCP
          livenessProbe:
            TCPSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 1
